import { CashflowFile, CashflowSummary } from '@app/features/cashflows/models';

const cashflowfile: CashflowFile = {
  id: 'b1e400e5-a512-437e-8cf1-422bc083b175',
  clientName: 'Katerra Inc',
  filename: 'A test cashflow file.xlsx',
  uploadDate: '2020-07-08T12:59:08.029821Z',
  uploadedBy: 'Operations Portal',
  status: 'CASHFLOW_CREATION_END',
  cashflowRowCount: 10,
  cashflowTotals: [],
  processingFailureMessages: null,
  processedBy: null,
};

const cashflowfileWithTotals: CashflowFile = {
  id: 'b1e400e5-a512-437e-8cf1-422bc083b175',
  clientName: 'Katerra Inc',
  filename: 'A test cashflow file.xlsx',
  uploadDate: '2020-07-08T12:59:08.029821Z',
  uploadedBy: 'Operations Portal',
  status: 'CASHFLOW_CREATION_END',
  cashflowRowCount: 10,
  processedBy: 'Batman',
  cashflowTotals: [
    {
      cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
      currency: 'GBP',
      totalOriginalValue: 1100.0,
      totalInitialFundingAmount: 190.0,
      totalCashflows: 110,
      totalValidCashflows: 180,
      totalInvalidCashflows: 120,
      totalInvalidOriginalValue: 120.0,
      totalInvalidInitialFundingAmount: 118.0,
    },
    {
      cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
      currency: 'USD',
      totalOriginalValue: 100.0,
      totalInitialFundingAmount: 90.0,
      totalCashflows: 10,
      totalValidCashflows: 8,
      totalInvalidCashflows: 2,
      totalInvalidOriginalValue: 20.0,
      totalInvalidInitialFundingAmount: 18.0,
    },
  ],
  processingFailureMessages: null,
};

const cashflowfileWithFailures: CashflowFile = {
  id: 'b1e400e5-a512-437e-8cf1-422bc083b175',
  clientName: 'Katerra Inc',
  filename: 'A test cashflow file.xlsx',
  uploadDate: '2020-07-08T12:59:08.029821Z',
  uploadedBy: 'Operations Portal',
  status: 'FAILED_PROCESSING',
  cashflowRowCount: 10,
  processedBy: null,
  processingFailureMessages: [
    {
      message: 'field is required',
      rowFailed: 2,
    },
    {
      message: 'field is required',
      rowFailed: 4,
    },
  ],
};

const cashflowfileRejected: CashflowFile = {
  id: '7e7ed685-1cf7-4854-8be7-63b6a94c7de3',
  clientName: 'Katerra Inc',
  filename: 'DEVDATA.txt',
  uploadDate: '2020-07-12T20:23:42.318484Z',
  uploadedBy: 'Operations Portal',
  cashflowRowCount: 0,
  status: 'REJECTED',
  processingFailureMessages: null,
  rejectionDetail: {
    user: 'ops-portal-user',
    message: 'Date too far in the future',
    date: '2020-08-07 12:38:46',
  },
};

const validCashflows: CashflowSummary[] = [
  {
    id: 'abc-1',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc1',
      name: 'Entity Two',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'GBP',
    originalValue: 1000.0,
    state: 'PENDING_PROCESSING',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 1000,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-2',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '',
      name: '',
      role: '',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'GBP',
    originalValue: 9999.0,
    state: 'APPROVED',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc2',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
];

const invalidCashflows: CashflowSummary[] = [
  {
    id: 'abc-3',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '123abc3',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '',
      name: '',
      role: '',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8888.0,
    state: 'REJECTED',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'SINGLE_SUPPLIER',
        message: 'Must be one and only one supplier on the cashflow',
      },
      {
        code: 'SUPPLIER_NOT_ON_CONTRACT',
        message: 'The SUPPLIER is not on the Contract',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc3',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
];

const cashflowFailures: CashflowSummary[] = [
  {
    id: 'abc-4',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CONTRACT_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CONTRACT_NOT_FOUND',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc4',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-5',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'ERROR_IN_PROCESSSING',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'NEW_UNKNOWN_CODE',
        message: null,
      },
    ],
    bufferPeriod: 2,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc5',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-6',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    contract: undefined,
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'COUNTERPARTY_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'COUNTERPARTY_NOT_FOUND',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc6',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-7',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id2',
      name: 'the second contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CASHFLOW_CONFLICT',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CASHFLOW_CONFLICT',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc7',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
];

const cashflows: CashflowSummary[] = [...validCashflows, ...invalidCashflows, ...cashflowFailures];

export {
  cashflowfile,
  cashflowfileWithTotals,
  cashflowfileWithFailures,
  cashflowfileRejected,
  invalidCashflows,
  cashflowFailures,
  validCashflows,
  cashflows,
};
