export enum NotCreated {
  END_PROCESSING = 'END_PROCESSING',
  CASHFLOW_CREATION_START = 'CASHFLOW_CREATION_START',
  PENDING_PROCESSING = 'PENDING_PROCESSING',
  START_PROCESSING = 'START_PROCESSING',
  FAILED_PROCESSING = 'FAILED_PROCESSING',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
}

export enum Rejected {
  REJECTED = 'REJECTED',
}

export enum Originated {
  START_ORIGINATION = 'START_ORIGINATION',
  AWAITING_INTERNAL_APPROVAL = 'AWAITING_INTERNAL_APPROVAL',
  AWAITING_CLIENT_APPROVAL = 'AWAITING_CLIENT_APPROVAL',
}

export enum Submitted {
  SUBMITTED_TO_TRADE = 'SUBMITTED_TO_TRADE',
}
