import { CashflowFile, CashflowSummary, CashflowTotal } from '../../models';
import { CashflowFileFacility } from '@cashflows/models/cashflow-file';

const CASHFLOWFILE_IN_AWAITING_INTERNAL_APPROVAL: CashflowFile = {
  id: 'b1e400e5-a512-437e-8cf1-422bc083b175',
  clientName: 'Katerra Inc',
  filename: 'A test cashflow file.xlsx',
  uploadDate: '2020-07-08T12:59:08.029821Z',
  uploadedBy: 'Operations Portal',
  status: 'AWAITING_INTERNAL_APPROVAL',
  cashflowRowCount: 10,
  cashflowTotals: [],
  processingFailureMessages: null,
};

const CASHFLOWFILE_IN_START_ORIGINATION: CashflowFile = {
  id: 'b1e400e5-a512-437e-8cf1-422bc083b175',
  clientName: 'Katerra Inc',
  filename: 'A test cashflow file.xlsx',
  uploadDate: '2020-07-08T12:59:08.029821Z',
  uploadedBy: 'Operations Portal',
  status: 'START_ORIGINATION',
  cashflowRowCount: 10,
  cashflowTotals: [],
  processingFailureMessages: null,
};

const CASHFLOWS: CashflowSummary[] = [
  // a 'valid' record; entity one Role is 'Account Debtor'. The Contract and Currency match CASHFLOW_TOTALS
  {
    id: 'abc-1',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc1',
      name: 'Entity Two',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 1000.0,
    state: 'AWAITING_INTERNAL_APPROVAL',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-26',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 1001.0,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // excluded due to role of entity one
  {
    id: 'abc-2',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '',
      name: '',
      role: '',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 9999.0,
    state: 'APPROVED',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2021-01-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc2',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // REJECTED. The Contract and Currency match CASHFLOW_TOTALS
  {
    id: 'abc-3',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '123abc3',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '',
      name: '',
      role: '',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8888.0,
    state: 'REJECTED',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'SINGLE_SUPPLIER',
        message: 'Must be one and only one supplier on the cashflow',
      },
      {
        code: 'SUPPLIER_NOT_ON_CONTRACT',
        message: 'The SUPPLIER is not on the Contract',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc3',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // CONTRACT_NOT_FOUND. The Contract and Currency match CASHFLOW_TOTALS
  {
    id: 'abc-4',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CONTRACT_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CONTRACT_NOT_FOUND',
        message: 'Contract not found',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc4',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // ERROR_IN_PROCESSSING. The Contract and Currency match CASHFLOW_TOTALS
  {
    id: 'abc-5',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'ERROR_IN_PROCESSSING',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'NEW_UNKNOWN_CODE',
        message: null,
      },
    ],
    bufferPeriod: 2,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc5',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // COUNTERPARTY_NOT_FOUND. Not matched with CASHFLOW_TOTALS due to contract
  {
    id: 'abc-6',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    contract: undefined,
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'COUNTERPARTY_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'COUNTERPARTY_NOT_FOUND',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc6',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // CASHFLOW_CONFLICT. Not matched with CASHFLOW_TOTALS due to contract
  {
    id: 'abc-7',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id2',
      name: 'the second contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CASHFLOW_CONFLICT',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CASHFLOW_CONFLICT',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc7',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // CASHFLOW_PROCESSING_ERROR. Unexpected error processing the cashflow
  {
    id: 'abc-7',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id2',
      name: 'the second contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CASHFLOW_CONFLICT',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CASHFLOW_PROCESSING_ERROR',
        message: null,
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc7',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // A valid record, grouped with row 0
  {
    id: 'abc-8',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc4',
      name: 'Entity Four',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 1000.0,
    state: 'AWAITING_INTERNAL_APPROVAL',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 1001.0,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // A valid record, grouped with row 0 and 7
  {
    id: 'abc-9',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc4',
      name: 'Entity Four',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 1000.0,
    state: 'AWAITING_INTERNAL_APPROVAL',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 9999.99,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // A valid record, for currency GBP that matches the CASHFLOW_TOTALS[0]
  {
    id: 'abc-10',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc4',
      name: 'Entity Four',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'GBP',
    originalValue: 1000.0,
    state: 'AWAITING_INTERNAL_APPROVAL',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 999.49,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  // A valid record, grouped with row 9
  {
    id: 'abc-11',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '456def',
      name: 'Entity One',
      role: 'Account Debtor',
    },
    entityTwo: {
      id: '123abc4',
      name: 'Entity Four',
      role: 'Affiliate-Seller',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'GBP',
    originalValue: 1000.0,
    state: 'AWAITING_INTERNAL_APPROVAL',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0001',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [],
    bufferPeriod: 2,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc1',
    settlementAmount: 10789.49,
    annualisedMarginRate: 1.01,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
];

const CASHFLOW_TOTALS: CashflowTotal[] = [
  {
    referenceRateType: 'LIBOR',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    currency: 'GBP',
    contractId: 'the-contract-id1',
    contractName: 'contract-123-name',
    contractAdvanceRate: 90,
    contractSpread: 15,
    acceptanceDate: '2020-10-01',
    totalOriginalValue: 100.0,
    totalInitialFundingAmount: 90.0,
    totalDiscountAmount: 5,
    totalPaymentAmount: 85.5,
    totalCashflows: 30,
    referenceRateDate: '2020-08-02',
    multipleMargins: false,
    multipleAdvanceRate: false,
    cashflowFile: {
      id: 'cf_id_1',
      clientName: 'ABC Corp',
      filename: 'filename.xlsx',
      uploadDate: '2020-08-01',
      uploadedBy: 'Dave',
      status: 'PENDING_PROCESSING',
      cashflowRowCount: 10,
      processingFailureMessages: [],
      processedBy: 'Batman',
    },
  },
  {
    referenceRateType: 'LIBOR',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    currency: 'USD',
    contractId: 'the-contract-id1',
    contractName: 'contract-123-name',
    contractAdvanceRate: 90,
    contractSpread: 15,
    acceptanceDate: '2020-10-01',
    totalOriginalValue: 100.0,
    totalInitialFundingAmount: 90.0,
    totalDiscountAmount: 5,
    totalPaymentAmount: 85.5,
    totalCashflows: 30,
    referenceRateDate: '2020-08-02',
    multipleMargins: false,
    multipleAdvanceRate: false,
    cashflowFile: {
      id: 'cf_id_1',
      clientName: 'ABC Corp',
      filename: 'filename.xlsx',
      uploadDate: '2020-08-01',
      uploadedBy: 'Dave',
      status: 'PENDING_PROCESSING',
      cashflowRowCount: 10,
      processingFailureMessages: [],
      processedBy: 'Robin',
    },
  },
];

const CASHFLOW_FILE_FACILITY: CashflowFileFacility[] = [
  {
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityId: '456def',
    contractId: 'the-contract-id1',
    facilityId: 'the-facility-id',
    currency: 'USD',
    limit: 20000,
    exposure: 15000,
    insuranceLimit: 6000,
    insuranceAvailable: 7000,
    insuranceLimitType: 'DCL',
  },
  {
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityId: '456def',
    contractId: 'the-contract-id1',
    facilityId: 'the-facility-id',
    currency: 'GBP',
    limit: 20000,
    exposure: 13789.99,
    insuranceLimit: 6000,
    insuranceAvailable: 7000,
    insuranceLimitType: 'DCL',
  },
];

export {
  CASHFLOWFILE_IN_AWAITING_INTERNAL_APPROVAL,
  CASHFLOWFILE_IN_START_ORIGINATION,
  CASHFLOWS,
  CASHFLOW_TOTALS,
  CASHFLOW_FILE_FACILITY,
};
