import { CashflowSummary, ProposalCashflowsWithFacility } from '@cashflows/models/cashflow-summary';
import { Entity } from '@entities/models/entity.model';

const PROPOSAL_CASHFLOWS_WITH_FACILITIES: ProposalCashflowsWithFacility[] = [
  {
    accountDebtorEntityId: '456def',
    accountDebtorName: 'Entity One',
    availableLimit: 5000,
    cashflows: [
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc1',
          name: 'Entity Two',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-1',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-26',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-8',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-9',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 9999.99,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
    ],
    contractId: 'the-contract-id1',
    currency: 'USD',
    currentOutstanding: 12300,
    latestMaturityDate: '2020-10-26',
    limit: 20000,
    noOfCashflows: 3,
    fundingAmount: 2700,
    totalIfPurchased: 15000,
    utilisation: 75,
    insuranceLimit: 6000,
    insuranceAvailable: 7000,
    insuranceLimitType: 'DCL',
    insuranceType: 'INSURED',
  },
  {
    accountDebtorEntityId: '456def',
    accountDebtorName: 'Entity One',
    availableLimit: 6210.01,
    cashflows: [
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'GBP',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-10',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 999.49,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'GBP',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-11',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 10789.49,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
    ],
    contractId: 'the-contract-id1',
    currency: 'GBP',
    currentOutstanding: 11989.99,
    latestMaturityDate: '2020-10-23',
    limit: 20000,
    noOfCashflows: 2,
    fundingAmount: 1800,
    totalIfPurchased: 13789.99,
    utilisation: 68.95,
    insuranceLimit: 6000,
    insuranceAvailable: 7000,
    insuranceLimitType: 'DCL',
    insuranceType: 'INSURED',
  },
];

const TAB_PROPOSAL_CASHFLOWS_WITH_FACILITIES: ProposalCashflowsWithFacility[] = [
  {
    accountDebtorEntityId: '456def',
    accountDebtorName: 'Entity One',
    availableLimit: 5000,
    cashflows: [
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc1',
          name: 'Entity Two',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-1',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-26',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-8',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-9',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 9999.99,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
    ],
    contractId: 'the-contract-id1',
    currency: 'USD',
    currentOutstanding: 12300,
    latestMaturityDate: '2020-10-26',
    limit: 20000,
    noOfCashflows: 3,
    fundingAmount: 2700,
    totalIfPurchased: 15000,
    utilisation: 75,
    insuranceLimit: 6000,
    insuranceAvailable: 7000,
    insuranceLimitType: 'DCL',
    insuranceType: 'INSURED',
  },
];

const PROPOSAL_CASHFLOWS_WITH_FACILITIES_WHEN_NO_FACILITIES: ProposalCashflowsWithFacility[] = [
  {
    accountDebtorEntityId: '456def',
    accountDebtorName: 'Entity One',
    availableLimit: 0,
    cashflows: [
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc1',
          name: 'Entity Two',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-1',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-26',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-8',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 1001,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'USD',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-9',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 9999.99,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
    ],
    contractId: 'the-contract-id1',
    currency: 'USD',
    currentOutstanding: 0,
    latestMaturityDate: '2020-10-26',
    limit: 0,
    noOfCashflows: 3,
    fundingAmount: 2700,
    totalIfPurchased: 0,
    utilisation: 0,
    insuranceLimit: 0,
    insuranceAvailable: 0,
    insuranceLimitType: 'DCL',
    insuranceType: 'INSURED',
  },
  {
    accountDebtorEntityId: '456def',
    accountDebtorName: 'Entity One',
    availableLimit: 0,
    cashflows: [
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'GBP',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-10',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 999.49,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
      {
        acceptanceDate: '2020-08-13',
        adjustment: 15,
        advanceRate: 90,
        annualisedMarginRate: 1.01,
        bufferPeriod: 2,
        cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
        cashflowReference: 'CR_123abc1',
        certifiedAmount: 123.34,
        contract: {
          id: 'the-contract-id1',
          name: 'the contract name',
        },
        currency: 'GBP',
        documentReference: 'ABCD0001',
        entityOne: {
          id: '456def',
          name: 'Entity One',
          role: 'Account Debtor',
        },
        entityTwo: {
          id: '123abc4',
          name: 'Entity Four',
          role: 'Affiliate-Seller',
        },
        fundingAmount: 900,
        id: 'abc-11',
        issueDate: '2020-05-09',
        leadDays: 14,
        referenceRate: 10,
        maturityDate: '2020-10-23',
        originalDueDate: '2020-05-10',
        originalValue: 1000,
        reasonForFailure: [],
        settlementAmount: 10789.49,
        state: 'AWAITING_INTERNAL_APPROVAL',
        unitPrice: 123.34,
        hasFailures: false,
        insuranceType: 'INSURED',
      },
    ],
    contractId: 'the-contract-id1',
    currency: 'GBP',
    currentOutstanding: 0,
    latestMaturityDate: '2020-10-23',
    limit: 0,
    noOfCashflows: 2,
    fundingAmount: 1800,
    totalIfPurchased: 0,
    utilisation: 0,
    insuranceLimit: 0,
    insuranceAvailable: 0,
    insuranceLimitType: 'DCL',
    insuranceType: 'INSURED',
  },
];

const TAB_REJECTED_CASHFLOWS: CashflowSummary[] = [
  {
    id: 'abc-3',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b175',
    entityOne: {
      id: '123abc3',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '',
      name: '',
      role: '',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8888.0,
    state: 'REJECTED',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'SINGLE_SUPPLIER',
        message: 'Must be one and only one supplier on the cashflow',
      },
      {
        code: 'SUPPLIER_NOT_ON_CONTRACT',
        message: 'The SUPPLIER is not on the Contract',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc3',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: false,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-4',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'CONTRACT_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CONTRACT_NOT_FOUND',
        message: 'Contract not found',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: '2020-08-13',
    cashflowReference: 'CR_123abc4',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: true,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-5',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id1',
      name: 'the contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887.0,
    state: 'ERROR_IN_PROCESSSING',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900.0,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'NEW_UNKNOWN_CODE',
        message: 'NEW_UNKNOWN_CODE',
      },
    ],
    bufferPeriod: 2,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc5',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: true,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-6',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: undefined,
      name: 'Entity One',
      role: undefined,
    },
    entityTwo: {
      id: undefined,
      name: 'Entity Three',
      role: undefined,
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887,
    state: 'COUNTERPARTY_NOT_FOUND',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'COUNTERPARTY_NOT_FOUND',
        message: 'COUNTERPARTY_NOT_FOUND',
      },
    ],
    contract: undefined,
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc6',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: true,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-7',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id2',
      name: 'the second contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887,
    state: 'CASHFLOW_CONFLICT',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CASHFLOW_CONFLICT',
        message: 'CASHFLOW_CONFLICT',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc7',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: true,
    insuranceType: 'INSURED',
  },
  {
    id: 'abc-7',
    cashflowFileId: 'b1e400e5-a512-437e-8cf1-422bc083b176',
    entityOne: {
      id: '123abc5',
      name: 'Entity One',
      role: 'Affiliate-Seller',
    },
    entityTwo: {
      id: '789ghi',
      name: 'Entity Three',
      role: 'Account Debtor',
    },
    contract: {
      id: 'the-contract-id2',
      name: 'the second contract name',
    },
    issueDate: '2020-05-09',
    originalDueDate: '2020-05-10',
    currency: 'USD',
    originalValue: 8887,
    state: 'CASHFLOW_CONFLICT',
    unitPrice: 123.34,
    certifiedAmount: 123.34,
    documentReference: 'ABCD0002',
    fundingAmount: 900,
    advanceRate: 90,
    maturityDate: '2020-10-23',
    reasonForFailure: [
      {
        code: 'CASHFLOW_PROCESSING_ERROR',
        message: 'Unexpected error when processing the cashflow',
      },
    ],
    bufferPeriod: undefined,
    acceptanceDate: undefined,
    cashflowReference: 'CR_123abc7',
    settlementAmount: 1002,
    annualisedMarginRate: 1.21,
    adjustment: 15,
    leadDays: 14,
    referenceRate: 10,
    hasFailures: true,
    insuranceType: 'INSURED',
  },
];

// @ts-ignore
const EXPECTED_SELLERS: Entity = [
  {
    id: '123abc1',
    name: 'Entity Two',
    role: 'Affiliate-Seller',
  },
  {
    id: '123abc3',
    name: 'Entity One',
    role: 'Affiliate-Seller',
  },
  {
    id: '123abc5',
    name: 'Entity One',
    role: 'Affiliate-Seller',
  },
  {
    id: '123abc4',
    name: 'Entity Four',
    role: 'Affiliate-Seller',
  },
];

export {
  PROPOSAL_CASHFLOWS_WITH_FACILITIES,
  TAB_PROPOSAL_CASHFLOWS_WITH_FACILITIES,
  PROPOSAL_CASHFLOWS_WITH_FACILITIES_WHEN_NO_FACILITIES,
  TAB_REJECTED_CASHFLOWS,
  EXPECTED_SELLERS,
};
